# Warning: this file is auto-generated. Do not edit.

from ctypes import c_int
import enum


class Result(enum.Enum):
    SUCCESS = c_int(0)
    TIMEOUT_EXPIRED = c_int(1)
    SESSION_LOSS_PENDING = c_int(3)
    EVENT_UNAVAILABLE = c_int(4)
    SPACE_BOUNDS_UNAVAILABLE = c_int(7)
    SESSION_NOT_FOCUSED = c_int(8)
    FRAME_DISCARDED = c_int(9)
    ERROR_VALIDATION_FAILURE = c_int(-1)
    ERROR_RUNTIME_FAILURE = c_int(-2)
    ERROR_OUT_OF_MEMORY = c_int(-3)
    ERROR_API_VERSION_UNSUPPORTED = c_int(-4)
    ERROR_INITIALIZATION_FAILED = c_int(-6)
    ERROR_FUNCTION_UNSUPPORTED = c_int(-7)
    ERROR_FEATURE_UNSUPPORTED = c_int(-8)
    ERROR_EXTENSION_NOT_PRESENT = c_int(-9)
    ERROR_LIMIT_REACHED = c_int(-10)
    ERROR_SIZE_INSUFFICIENT = c_int(-11)
    ERROR_HANDLE_INVALID = c_int(-12)
    ERROR_INSTANCE_LOST = c_int(-13)
    ERROR_SESSION_RUNNING = c_int(-14)
    ERROR_SESSION_NOT_RUNNING = c_int(-16)
    ERROR_SESSION_LOST = c_int(-17)
    ERROR_SYSTEM_INVALID = c_int(-18)
    ERROR_PATH_INVALID = c_int(-19)
    ERROR_PATH_COUNT_EXCEEDED = c_int(-20)
    ERROR_PATH_FORMAT_INVALID = c_int(-21)
    ERROR_PATH_UNSUPPORTED = c_int(-22)
    ERROR_LAYER_INVALID = c_int(-23)
    ERROR_LAYER_LIMIT_EXCEEDED = c_int(-24)
    ERROR_SWAPCHAIN_RECT_INVALID = c_int(-25)
    ERROR_SWAPCHAIN_FORMAT_UNSUPPORTED = c_int(-26)
    ERROR_ACTION_TYPE_MISMATCH = c_int(-27)
    ERROR_SESSION_NOT_READY = c_int(-28)
    ERROR_SESSION_NOT_STOPPING = c_int(-29)
    ERROR_TIME_INVALID = c_int(-30)
    ERROR_REFERENCE_SPACE_UNSUPPORTED = c_int(-31)
    ERROR_FILE_ACCESS_ERROR = c_int(-32)
    ERROR_FILE_CONTENTS_INVALID = c_int(-33)
    ERROR_FORM_FACTOR_UNSUPPORTED = c_int(-34)
    ERROR_FORM_FACTOR_UNAVAILABLE = c_int(-35)
    ERROR_API_LAYER_NOT_PRESENT = c_int(-36)
    ERROR_CALL_ORDER_INVALID = c_int(-37)
    ERROR_GRAPHICS_DEVICE_INVALID = c_int(-38)
    ERROR_POSE_INVALID = c_int(-39)
    ERROR_INDEX_OUT_OF_RANGE = c_int(-40)
    ERROR_VIEW_CONFIGURATION_TYPE_UNSUPPORTED = c_int(-41)
    ERROR_ENVIRONMENT_BLEND_MODE_UNSUPPORTED = c_int(-42)
    ERROR_NAME_DUPLICATED = c_int(-44)
    ERROR_NAME_INVALID = c_int(-45)
    ERROR_ACTIONSET_NOT_ATTACHED = c_int(-46)
    ERROR_ACTIONSETS_ALREADY_ATTACHED = c_int(-47)
    ERROR_LOCALIZED_NAME_DUPLICATED = c_int(-48)
    ERROR_LOCALIZED_NAME_INVALID = c_int(-49)
    ERROR_GRAPHICS_REQUIREMENTS_CALL_MISSING = c_int(-50)
    ERROR_RUNTIME_UNAVAILABLE = c_int(-51)
    ERROR_ANDROID_THREAD_SETTINGS_ID_INVALID_KHR = c_int(-1000003000)
    ERROR_ANDROID_THREAD_SETTINGS_FAILURE_KHR = c_int(-1000003001)
    ERROR_CREATE_SPATIAL_ANCHOR_FAILED_MSFT = c_int(-1000039001)
    ERROR_SECONDARY_VIEW_CONFIGURATION_TYPE_NOT_ENABLED_MSFT = c_int(-1000053000)
    ERROR_CONTROLLER_MODEL_KEY_INVALID_MSFT = c_int(-1000055000)
    ERROR_REPROJECTION_MODE_UNSUPPORTED_MSFT = c_int(-1000066000)
    ERROR_COMPUTE_NEW_SCENE_NOT_COMPLETED_MSFT = c_int(-1000097000)
    ERROR_SCENE_COMPONENT_ID_INVALID_MSFT = c_int(-1000097001)
    ERROR_SCENE_COMPONENT_TYPE_MISMATCH_MSFT = c_int(-1000097002)
    ERROR_SCENE_MESH_BUFFER_ID_INVALID_MSFT = c_int(-1000097003)
    ERROR_SCENE_COMPUTE_FEATURE_INCOMPATIBLE_MSFT = c_int(-1000097004)
    ERROR_SCENE_COMPUTE_CONSISTENCY_MISMATCH_MSFT = c_int(-1000097005)
    ERROR_DISPLAY_REFRESH_RATE_UNSUPPORTED_FB = c_int(-1000101000)
    ERROR_COLOR_SPACE_UNSUPPORTED_FB = c_int(-1000108000)
    ERROR_SPATIAL_ANCHOR_NAME_NOT_FOUND_MSFT = c_int(-1000142001)
    ERROR_SPATIAL_ANCHOR_NAME_INVALID_MSFT = c_int(-1000142002)


class StructureType(enum.Enum):
    UNKNOWN = c_int(0)
    API_LAYER_PROPERTIES = c_int(1)
    EXTENSION_PROPERTIES = c_int(2)
    INSTANCE_CREATE_INFO = c_int(3)
    SYSTEM_GET_INFO = c_int(4)
    SYSTEM_PROPERTIES = c_int(5)
    VIEW_LOCATE_INFO = c_int(6)
    VIEW = c_int(7)
    SESSION_CREATE_INFO = c_int(8)
    SWAPCHAIN_CREATE_INFO = c_int(9)
    SESSION_BEGIN_INFO = c_int(10)
    VIEW_STATE = c_int(11)
    FRAME_END_INFO = c_int(12)
    HAPTIC_VIBRATION = c_int(13)
    EVENT_DATA_BUFFER = c_int(16)
    EVENT_DATA_INSTANCE_LOSS_PENDING = c_int(17)
    EVENT_DATA_SESSION_STATE_CHANGED = c_int(18)
    ACTION_STATE_BOOLEAN = c_int(23)
    ACTION_STATE_FLOAT = c_int(24)
    ACTION_STATE_VECTOR2F = c_int(25)
    ACTION_STATE_POSE = c_int(27)
    ACTION_SET_CREATE_INFO = c_int(28)
    ACTION_CREATE_INFO = c_int(29)
    INSTANCE_PROPERTIES = c_int(32)
    FRAME_WAIT_INFO = c_int(33)
    COMPOSITION_LAYER_PROJECTION = c_int(35)
    COMPOSITION_LAYER_QUAD = c_int(36)
    REFERENCE_SPACE_CREATE_INFO = c_int(37)
    ACTION_SPACE_CREATE_INFO = c_int(38)
    EVENT_DATA_REFERENCE_SPACE_CHANGE_PENDING = c_int(40)
    VIEW_CONFIGURATION_VIEW = c_int(41)
    SPACE_LOCATION = c_int(42)
    SPACE_VELOCITY = c_int(43)
    FRAME_STATE = c_int(44)
    VIEW_CONFIGURATION_PROPERTIES = c_int(45)
    FRAME_BEGIN_INFO = c_int(46)
    COMPOSITION_LAYER_PROJECTION_VIEW = c_int(48)
    EVENT_DATA_EVENTS_LOST = c_int(49)
    INTERACTION_PROFILE_SUGGESTED_BINDING = c_int(51)
    EVENT_DATA_INTERACTION_PROFILE_CHANGED = c_int(52)
    INTERACTION_PROFILE_STATE = c_int(53)
    SWAPCHAIN_IMAGE_ACQUIRE_INFO = c_int(55)
    SWAPCHAIN_IMAGE_WAIT_INFO = c_int(56)
    SWAPCHAIN_IMAGE_RELEASE_INFO = c_int(57)
    ACTION_STATE_GET_INFO = c_int(58)
    HAPTIC_ACTION_INFO = c_int(59)
    SESSION_ACTION_SETS_ATTACH_INFO = c_int(60)
    ACTIONS_SYNC_INFO = c_int(61)
    BOUND_SOURCES_FOR_ACTION_ENUMERATE_INFO = c_int(62)
    INPUT_SOURCE_LOCALIZED_NAME_GET_INFO = c_int(63)
    COMPOSITION_LAYER_CUBE_KHR = c_int(1000006000)
    INSTANCE_CREATE_INFO_ANDROID_KHR = c_int(1000008000)
    COMPOSITION_LAYER_DEPTH_INFO_KHR = c_int(1000010000)
    VULKAN_SWAPCHAIN_FORMAT_LIST_CREATE_INFO_KHR = c_int(1000014000)
    EVENT_DATA_PERF_SETTINGS_EXT = c_int(1000015000)
    COMPOSITION_LAYER_CYLINDER_KHR = c_int(1000017000)
    COMPOSITION_LAYER_EQUIRECT_KHR = c_int(1000018000)
    DEBUG_UTILS_OBJECT_NAME_INFO_EXT = c_int(1000019000)
    DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT = c_int(1000019001)
    DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT = c_int(1000019002)
    DEBUG_UTILS_LABEL_EXT = c_int(1000019003)
    GRAPHICS_BINDING_OPENGL_WIN32_KHR = c_int(1000023000)
    GRAPHICS_BINDING_OPENGL_XLIB_KHR = c_int(1000023001)
    GRAPHICS_BINDING_OPENGL_XCB_KHR = c_int(1000023002)
    GRAPHICS_BINDING_OPENGL_WAYLAND_KHR = c_int(1000023003)
    SWAPCHAIN_IMAGE_OPENGL_KHR = c_int(1000023004)
    GRAPHICS_REQUIREMENTS_OPENGL_KHR = c_int(1000023005)
    GRAPHICS_BINDING_OPENGL_ES_ANDROID_KHR = c_int(1000024001)
    SWAPCHAIN_IMAGE_OPENGL_ES_KHR = c_int(1000024002)
    GRAPHICS_REQUIREMENTS_OPENGL_ES_KHR = c_int(1000024003)
    GRAPHICS_BINDING_VULKAN_KHR = c_int(1000025000)
    SWAPCHAIN_IMAGE_VULKAN_KHR = c_int(1000025001)
    GRAPHICS_REQUIREMENTS_VULKAN_KHR = c_int(1000025002)
    GRAPHICS_BINDING_D3D11_KHR = c_int(1000027000)
    SWAPCHAIN_IMAGE_D3D11_KHR = c_int(1000027001)
    GRAPHICS_REQUIREMENTS_D3D11_KHR = c_int(1000027002)
    GRAPHICS_BINDING_D3D12_KHR = c_int(1000028000)
    SWAPCHAIN_IMAGE_D3D12_KHR = c_int(1000028001)
    GRAPHICS_REQUIREMENTS_D3D12_KHR = c_int(1000028002)
    SYSTEM_EYE_GAZE_INTERACTION_PROPERTIES_EXT = c_int(1000030000)
    EYE_GAZE_SAMPLE_TIME_EXT = c_int(1000030001)
    VISIBILITY_MASK_KHR = c_int(1000031000)
    EVENT_DATA_VISIBILITY_MASK_CHANGED_KHR = c_int(1000031001)
    SESSION_CREATE_INFO_OVERLAY_EXTX = c_int(1000033000)
    EVENT_DATA_MAIN_SESSION_VISIBILITY_CHANGED_EXTX = c_int(1000033003)
    COMPOSITION_LAYER_COLOR_SCALE_BIAS_KHR = c_int(1000034000)
    SPATIAL_ANCHOR_CREATE_INFO_MSFT = c_int(1000039000)
    SPATIAL_ANCHOR_SPACE_CREATE_INFO_MSFT = c_int(1000039001)
    COMPOSITION_LAYER_IMAGE_LAYOUT_FB = c_int(1000040000)
    COMPOSITION_LAYER_ALPHA_BLEND_FB = c_int(1000041001)
    VIEW_CONFIGURATION_DEPTH_RANGE_EXT = c_int(1000046000)
    GRAPHICS_BINDING_EGL_MNDX = c_int(1000048004)
    SPATIAL_GRAPH_NODE_SPACE_CREATE_INFO_MSFT = c_int(1000049000)
    SYSTEM_HAND_TRACKING_PROPERTIES_EXT = c_int(1000051000)
    HAND_TRACKER_CREATE_INFO_EXT = c_int(1000051001)
    HAND_JOINTS_LOCATE_INFO_EXT = c_int(1000051002)
    HAND_JOINT_LOCATIONS_EXT = c_int(1000051003)
    HAND_JOINT_VELOCITIES_EXT = c_int(1000051004)
    SYSTEM_HAND_TRACKING_MESH_PROPERTIES_MSFT = c_int(1000052000)
    HAND_MESH_SPACE_CREATE_INFO_MSFT = c_int(1000052001)
    HAND_MESH_UPDATE_INFO_MSFT = c_int(1000052002)
    HAND_MESH_MSFT = c_int(1000052003)
    HAND_POSE_TYPE_INFO_MSFT = c_int(1000052004)
    SECONDARY_VIEW_CONFIGURATION_SESSION_BEGIN_INFO_MSFT = c_int(1000053000)
    SECONDARY_VIEW_CONFIGURATION_STATE_MSFT = c_int(1000053001)
    SECONDARY_VIEW_CONFIGURATION_FRAME_STATE_MSFT = c_int(1000053002)
    SECONDARY_VIEW_CONFIGURATION_FRAME_END_INFO_MSFT = c_int(1000053003)
    SECONDARY_VIEW_CONFIGURATION_LAYER_INFO_MSFT = c_int(1000053004)
    SECONDARY_VIEW_CONFIGURATION_SWAPCHAIN_CREATE_INFO_MSFT = c_int(1000053005)
    CONTROLLER_MODEL_KEY_STATE_MSFT = c_int(1000055000)
    CONTROLLER_MODEL_NODE_PROPERTIES_MSFT = c_int(1000055001)
    CONTROLLER_MODEL_PROPERTIES_MSFT = c_int(1000055002)
    CONTROLLER_MODEL_NODE_STATE_MSFT = c_int(1000055003)
    CONTROLLER_MODEL_STATE_MSFT = c_int(1000055004)
    VIEW_CONFIGURATION_VIEW_FOV_EPIC = c_int(1000059000)
    HOLOGRAPHIC_WINDOW_ATTACHMENT_MSFT = c_int(1000063000)
    COMPOSITION_LAYER_REPROJECTION_INFO_MSFT = c_int(1000066000)
    COMPOSITION_LAYER_REPROJECTION_PLANE_OVERRIDE_MSFT = c_int(1000066001)
    ANDROID_SURFACE_SWAPCHAIN_CREATE_INFO_FB = c_int(1000070000)
    COMPOSITION_LAYER_SECURE_CONTENT_FB = c_int(1000072000)
    INTERACTION_PROFILE_ANALOG_THRESHOLD_VALVE = c_int(1000079000)
    HAND_JOINTS_MOTION_RANGE_INFO_EXT = c_int(1000080000)
    LOADER_INIT_INFO_ANDROID_KHR = c_int(1000089000)
    VULKAN_INSTANCE_CREATE_INFO_KHR = c_int(1000090000)
    VULKAN_DEVICE_CREATE_INFO_KHR = c_int(1000090001)
    VULKAN_GRAPHICS_DEVICE_GET_INFO_KHR = c_int(1000090003)
    COMPOSITION_LAYER_EQUIRECT2_KHR = c_int(1000091000)
    SCENE_OBSERVER_CREATE_INFO_MSFT = c_int(1000097000)
    SCENE_CREATE_INFO_MSFT = c_int(1000097001)
    NEW_SCENE_COMPUTE_INFO_MSFT = c_int(1000097002)
    VISUAL_MESH_COMPUTE_LOD_INFO_MSFT = c_int(1000097003)
    SCENE_COMPONENTS_MSFT = c_int(1000097004)
    SCENE_COMPONENTS_GET_INFO_MSFT = c_int(1000097005)
    SCENE_COMPONENT_LOCATIONS_MSFT = c_int(1000097006)
    SCENE_COMPONENTS_LOCATE_INFO_MSFT = c_int(1000097007)
    SCENE_OBJECTS_MSFT = c_int(1000097008)
    SCENE_COMPONENT_PARENT_FILTER_INFO_MSFT = c_int(1000097009)
    SCENE_OBJECT_TYPES_FILTER_INFO_MSFT = c_int(1000097010)
    SCENE_PLANES_MSFT = c_int(1000097011)
    SCENE_PLANE_ALIGNMENT_FILTER_INFO_MSFT = c_int(1000097012)
    SCENE_MESHES_MSFT = c_int(1000097013)
    SCENE_MESH_BUFFERS_GET_INFO_MSFT = c_int(1000097014)
    SCENE_MESH_BUFFERS_MSFT = c_int(1000097015)
    SCENE_MESH_VERTEX_BUFFER_MSFT = c_int(1000097016)
    SCENE_MESH_INDICES_UINT32_MSFT = c_int(1000097017)
    SCENE_MESH_INDICES_UINT16_MSFT = c_int(1000097018)
    SERIALIZED_SCENE_FRAGMENT_DATA_GET_INFO_MSFT = c_int(1000098000)
    SCENE_DESERIALIZE_INFO_MSFT = c_int(1000098001)
    EVENT_DATA_DISPLAY_REFRESH_RATE_CHANGED_FB = c_int(1000101000)
    SYSTEM_COLOR_SPACE_PROPERTIES_FB = c_int(1000108000)
    FOVEATION_PROFILE_CREATE_INFO_FB = c_int(1000114000)
    SWAPCHAIN_CREATE_INFO_FOVEATION_FB = c_int(1000114001)
    SWAPCHAIN_STATE_FOVEATION_FB = c_int(1000114002)
    FOVEATION_LEVEL_PROFILE_CREATE_INFO_FB = c_int(1000115000)
    BINDING_MODIFICATIONS_KHR = c_int(1000120000)
    VIEW_LOCATE_FOVEATED_RENDERING_VARJO = c_int(1000121000)
    FOVEATED_VIEW_CONFIGURATION_VIEW_VARJO = c_int(1000121001)
    SYSTEM_FOVEATED_RENDERING_PROPERTIES_VARJO = c_int(1000121002)
    COMPOSITION_LAYER_DEPTH_TEST_VARJO = c_int(1000122000)
    SPATIAL_ANCHOR_PERSISTENCE_INFO_MSFT = c_int(1000142000)
    SPATIAL_ANCHOR_FROM_PERSISTED_ANCHOR_CREATE_INFO_MSFT = c_int(1000142001)
    SWAPCHAIN_IMAGE_FOVEATION_VULKAN_FB = c_int(1000160000)
    SWAPCHAIN_STATE_ANDROID_SURFACE_DIMENSIONS_FB = c_int(1000161000)
    SWAPCHAIN_STATE_SAMPLER_OPENGL_ES_FB = c_int(1000162000)
    SWAPCHAIN_STATE_SAMPLER_VULKAN_FB = c_int(1000163000)
    GRAPHICS_BINDING_VULKAN2_KHR = c_int(1000025000)
    SWAPCHAIN_IMAGE_VULKAN2_KHR = c_int(1000025001)
    GRAPHICS_REQUIREMENTS_VULKAN2_KHR = c_int(1000025002)


class FormFactor(enum.Enum):
    HEAD_MOUNTED_DISPLAY = c_int(1)
    HANDHELD_DISPLAY = c_int(2)


class ViewConfigurationType(enum.Enum):
    PRIMARY_MONO = c_int(1)
    PRIMARY_STEREO = c_int(2)
    PRIMARY_QUAD_VARJO = c_int(1000037000)
    SECONDARY_MONO_FIRST_PERSON_OBSERVER_MSFT = c_int(1000054000)


class EnvironmentBlendMode(enum.Enum):
    OPAQUE = c_int(1)
    ADDITIVE = c_int(2)
    ALPHA_BLEND = c_int(3)


class ReferenceSpaceType(enum.Enum):
    VIEW = c_int(1)
    LOCAL = c_int(2)
    STAGE = c_int(3)
    UNBOUNDED_MSFT = c_int(1000038000)
    COMBINED_EYE_VARJO = c_int(1000121000)


class ActionType(enum.Enum):
    BOOLEAN_INPUT = c_int(1)
    FLOAT_INPUT = c_int(2)
    VECTOR2F_INPUT = c_int(3)
    POSE_INPUT = c_int(4)
    VIBRATION_OUTPUT = c_int(100)


class EyeVisibility(enum.Enum):
    BOTH = c_int(0)
    LEFT = c_int(1)
    RIGHT = c_int(2)


class SessionState(enum.Enum):
    UNKNOWN = c_int(0)
    IDLE = c_int(1)
    READY = c_int(2)
    SYNCHRONIZED = c_int(3)
    VISIBLE = c_int(4)
    FOCUSED = c_int(5)
    STOPPING = c_int(6)
    LOSS_PENDING = c_int(7)
    EXITING = c_int(8)


class ObjectType(enum.Enum):
    UNKNOWN = c_int(0)
    INSTANCE = c_int(1)
    SESSION = c_int(2)
    SWAPCHAIN = c_int(3)
    SPACE = c_int(4)
    ACTION_SET = c_int(5)
    ACTION = c_int(6)
    DEBUG_UTILS_MESSENGER_EXT = c_int(1000019000)
    SPATIAL_ANCHOR_MSFT = c_int(1000039000)
    HAND_TRACKER_EXT = c_int(1000051000)
    SCENE_OBSERVER_MSFT = c_int(1000097000)
    SCENE_MSFT = c_int(1000097001)
    FOVEATION_PROFILE_FB = c_int(1000114000)
    SPATIAL_ANCHOR_STORE_CONNECTION_MSFT = c_int(1000142000)


class VisibilityMaskTypeKHR(enum.Enum):
    HIDDEN_TRIANGLE_MESH = c_int(1)
    VISIBLE_TRIANGLE_MESH = c_int(2)
    LINE_LOOP = c_int(3)


class PerfSettingsDomainEXT(enum.Enum):
    CPU = c_int(1)
    GPU = c_int(2)


class PerfSettingsSubDomainEXT(enum.Enum):
    COMPOSITING = c_int(1)
    RENDERING = c_int(2)
    THERMAL = c_int(3)


class PerfSettingsLevelEXT(enum.Enum):
    POWER_SAVINGS = c_int(0)
    SUSTAINED_LOW = c_int(25)
    SUSTAINED_HIGH = c_int(50)
    BOOST = c_int(75)


class PerfSettingsNotificationLevelEXT(enum.Enum):
    NORMAL = c_int(0)
    WARNING = c_int(25)
    IMPAIRED = c_int(75)


class BlendFactorFB(enum.Enum):
    ZERO = c_int(0)
    ONE = c_int(1)
    SRC_ALPHA = c_int(2)
    ONE_MINUS_SRC_ALPHA = c_int(3)
    DST_ALPHA = c_int(4)
    ONE_MINUS_DST_ALPHA = c_int(5)


class SpatialGraphNodeTypeMSFT(enum.Enum):
    STATIC = c_int(1)
    DYNAMIC = c_int(2)


class HandEXT(enum.Enum):
    LEFT = c_int(1)
    RIGHT = c_int(2)


class HandJointEXT(enum.Enum):
    PALM = c_int(0)
    WRIST = c_int(1)
    THUMB_METACARPAL = c_int(2)
    THUMB_PROXIMAL = c_int(3)
    THUMB_DISTAL = c_int(4)
    THUMB_TIP = c_int(5)
    INDEX_METACARPAL = c_int(6)
    INDEX_PROXIMAL = c_int(7)
    INDEX_INTERMEDIATE = c_int(8)
    INDEX_DISTAL = c_int(9)
    INDEX_TIP = c_int(10)
    MIDDLE_METACARPAL = c_int(11)
    MIDDLE_PROXIMAL = c_int(12)
    MIDDLE_INTERMEDIATE = c_int(13)
    MIDDLE_DISTAL = c_int(14)
    MIDDLE_TIP = c_int(15)
    RING_METACARPAL = c_int(16)
    RING_PROXIMAL = c_int(17)
    RING_INTERMEDIATE = c_int(18)
    RING_DISTAL = c_int(19)
    RING_TIP = c_int(20)
    LITTLE_METACARPAL = c_int(21)
    LITTLE_PROXIMAL = c_int(22)
    LITTLE_INTERMEDIATE = c_int(23)
    LITTLE_DISTAL = c_int(24)
    LITTLE_TIP = c_int(25)


class HandJointSetEXT(enum.Enum):
    DEFAULT = c_int(0)


class HandPoseTypeMSFT(enum.Enum):
    TRACKED = c_int(0)
    REFERENCE_OPEN_PALM = c_int(1)


class ReprojectionModeMSFT(enum.Enum):
    DEPTH = c_int(1)
    PLANAR_FROM_DEPTH = c_int(2)
    PLANAR_MANUAL = c_int(3)
    ORIENTATION_ONLY = c_int(4)


class HandJointsMotionRangeEXT(enum.Enum):
    UNOBSTRUCTED = c_int(1)
    CONFORMING_TO_CONTROLLER = c_int(2)


class SceneComputeFeatureMSFT(enum.Enum):
    PLANE = c_int(1)
    PLANE_MESH = c_int(2)
    VISUAL_MESH = c_int(3)
    COLLIDER_MESH = c_int(4)
    SERIALIZE_SCENE = c_int(1000098000)


class SceneComputeConsistencyMSFT(enum.Enum):
    SNAPSHOT_COMPLETE = c_int(1)
    SNAPSHOT_INCOMPLETE_FAST = c_int(2)
    OCCLUSION_OPTIMIZED = c_int(3)


class MeshComputeLodMSFT(enum.Enum):
    COARSE = c_int(1)
    MEDIUM = c_int(2)
    FINE = c_int(3)
    UNLIMITED = c_int(4)


class SceneComponentTypeMSFT(enum.Enum):
    INVALID = c_int(-1)
    OBJECT = c_int(1)
    PLANE = c_int(2)
    VISUAL_MESH = c_int(3)
    COLLIDER_MESH = c_int(4)
    SERIALIZED_SCENE_FRAGMENT = c_int(1000098000)


class SceneObjectTypeMSFT(enum.Enum):
    UNCATEGORIZED = c_int(-1)
    BACKGROUND = c_int(1)
    WALL = c_int(2)
    FLOOR = c_int(3)
    CEILING = c_int(4)
    PLATFORM = c_int(5)
    INFERRED = c_int(6)


class ScenePlaneAlignmentTypeMSFT(enum.Enum):
    NON_ORTHOGONAL = c_int(0)
    HORIZONTAL = c_int(1)
    VERTICAL = c_int(2)


class SceneComputeStateMSFT(enum.Enum):
    NONE = c_int(0)
    UPDATING = c_int(1)
    COMPLETED = c_int(2)
    COMPLETED_WITH_ERROR = c_int(3)


class ColorSpaceFB(enum.Enum):
    UNMANAGED = c_int(0)
    REC2020 = c_int(1)
    REC709 = c_int(2)
    RIFT_CV1 = c_int(3)
    RIFT_S = c_int(4)
    QUEST = c_int(5)
    P3 = c_int(6)
    ADOBE_RGB = c_int(7)


class FoveationLevelFB(enum.Enum):
    NONE = c_int(0)
    LOW = c_int(1)
    MEDIUM = c_int(2)
    HIGH = c_int(3)


class FoveationDynamicFB(enum.Enum):
    DISABLED = c_int(0)
    LEVEL_ENABLED = c_int(1)


__all__ = [
    "Result",
    "StructureType",
    "FormFactor",
    "ViewConfigurationType",
    "EnvironmentBlendMode",
    "ReferenceSpaceType",
    "ActionType",
    "EyeVisibility",
    "SessionState",
    "ObjectType",
    "VisibilityMaskTypeKHR",
    "PerfSettingsDomainEXT",
    "PerfSettingsSubDomainEXT",
    "PerfSettingsLevelEXT",
    "PerfSettingsNotificationLevelEXT",
    "BlendFactorFB",
    "SpatialGraphNodeTypeMSFT",
    "HandEXT",
    "HandJointEXT",
    "HandJointSetEXT",
    "HandPoseTypeMSFT",
    "ReprojectionModeMSFT",
    "HandJointsMotionRangeEXT",
    "SceneComputeFeatureMSFT",
    "SceneComputeConsistencyMSFT",
    "MeshComputeLodMSFT",
    "SceneComponentTypeMSFT",
    "SceneObjectTypeMSFT",
    "ScenePlaneAlignmentTypeMSFT",
    "SceneComputeStateMSFT",
    "ColorSpaceFB",
    "FoveationLevelFB",
    "FoveationDynamicFB",
]
